#ifndef UNAMANGEDCLOMODEL_GLOBAL_H
#define UNAMANGEDCLOMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef UNAMANGEDCLOMODEL_LIB
# define UNAMANGEDCLOMODEL_EXPORT Q_DECL_EXPORT
#else
# define UNAMANGEDCLOMODEL_EXPORT Q_DECL_IMPORT
#endif

#endif // UNAMANGEDCLOMODEL_GLOBAL_H
